// Shared policy data and per-package configuration resolution (SPEC §1, §8): a package's base
// namespace, the directory namespaces it declares (`src/render` → `render`) and the effective config
// of one file (the longest `namespaces` directory it sits in, else the base).
import { existsSync, readFileSync } from "node:fs"
import { dirname, join, relative, resolve, sep } from "node:path"

/** Bumping this changes every emitted part attribute (SPEC §3.1). */
export const HASH_VERSION = "v1"
export const DEFAULT_HASH_LENGTH = 6
export const PART_ATTR_PREFIX = "_cxclass_"

/** Dev-only attribute names (SPEC §5.5). */
export const DEV_ATTRS = {
    part: "_cxpart",
    component: "data-react-component",
    source: "data-file-source",
} as const

/** Roots on these tags become custom tags; everything else keeps its tag and gets a marker (SPEC §2.2). */
export const GENERIC_ROOT_TAGS: readonly string[] = ["div", "span"]

/** SVG elements whose `cx` attribute is geometry — the one `cx` JSX attribute that is not the removed part list (SPEC §5.3). */
export const SVG_GEOMETRY_CX: readonly string[] = ["circle", "ellipse", "radialGradient"]

/** Named slot props (`inputCx`): a `cx()` value the component spreads onto an inner element (SPEC §5.4). */
export const SLOT_PROP = /^[a-z][A-Za-z0-9]*Cx$/

/**
 * First line of every part-map module the workspace build generates (`libstylist build`): the build
 * removes a stale module only when it carries it, and `no-hash-literal` skips such a module.
 */
export const PART_MAP_HEADER = "// generated by libstylist (`libstylist build`) — do not edit; `libstylist build --check` fails on drift"
/** Where the workspace build writes the registry JSON when `css.registry` is unset, relative to the config's directory. */
export const DEFAULT_REGISTRY_FILE = "node_modules/.cache/libstylist/stylist-registry.json"

export const PREFIX_RE = /^[a-z][a-z0-9]*$/
export const PART_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/
export const TAG_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)+$/

export interface PackageStylistConfig {
    prefix: string
    /** Hash namespace (`core`, `app`, `player`, …). */
    namespace: string
    /** Tag segment; empty for the base namespace. */
    segment: string
    /** PascalCase word stripped from the front of component names (`Player`). */
    word: string
    hashLength: number
}

/** One entry of a `namespaces` field: the namespace (naming derived as for a package), or its full naming. */
export type RawNamespaceEntry = string | { namespace: string; segment?: string; word?: string }

export interface RawPackageStylistConfig {
    prefix?: string
    namespace?: string
    segment?: string
    word?: string
    hashLength?: number
    role?: string
    /**
     * Directory namespaces (SPEC §8): a package-relative posix directory (`src/render`) → the namespace
     * of the files under it. The longest directory containing a file wins; files outside every one use
     * the package's `namespace`.
     */
    namespaces?: Record<string, RawNamespaceEntry>
    /**
     * The package's source directories (package-relative posix directories): the JSX `gen-types` scans for
     * custom tags and the modules the workspace transform owns. Default {@link DEFAULT_SOURCES}.
     */
    sources?: string[]
}

/** The source directories of a package that declares none: `src`. */
export const DEFAULT_SOURCES: readonly string[] = ["src"]

/** A directory of a package whose files hash and name tags in a namespace of their own (SPEC §8). */
export interface DirectoryNamespace {
    /** Package-relative posix directory without a trailing slash (`src/render`). */
    dir: string
    /** The complete config of the files under it: the package's prefix and hash length, the directory's naming. */
    config: PackageStylistConfig
}

const capitalize = (s: string) => (s ? s[0].toUpperCase() + s.slice(1) : s)

/** Normalizes a `package.json` `libstylist` field into a complete package config. */
export function normalizePackageConfig(raw: RawPackageStylistConfig, where = "libstylist config"): PackageStylistConfig {
    const prefix = raw.prefix
    const namespace = raw.namespace
    if (!prefix || !PREFIX_RE.test(prefix)) throw new Error(`${where}: "prefix" must match ${PREFIX_RE}`)
    if (!namespace || !PREFIX_RE.test(namespace)) throw new Error(`${where}: "namespace" must match ${PREFIX_RE}`)
    const segment = raw.segment ?? (namespace === "core" ? "" : namespace)
    if (segment && !PREFIX_RE.test(segment)) throw new Error(`${where}: "segment" must match ${PREFIX_RE}`)
    const word = raw.word ?? capitalize(segment)
    const hashLength = raw.hashLength ?? DEFAULT_HASH_LENGTH
    if (!Number.isInteger(hashLength) || hashLength < 4 || hashLength > 12) throw new Error(`${where}: "hashLength" must be an integer in 4..12`)
    return { prefix, namespace, segment, word, hashLength }
}

const isObject = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v)

/**
 * Validates one `namespaces` key and returns it normalized (trailing slashes dropped): a
 * package-relative posix directory — no leading `/` or drive, no backslash, no empty, `.` or `..`
 * segment, no glob characters. Throws otherwise.
 */
export function normalizeNamespaceDir(key: string, where = "libstylist config"): string {
    const dir = key.replace(/\/+$/, "")
    const bad = (why: string) => new Error(`${where}.namespaces: "${key}" ${why} — keys are package-relative posix directories ("src/render")`)
    if (!dir) throw bad("names no directory")
    if (dir.startsWith("/") || /^[A-Za-z]:/.test(dir)) throw bad("is absolute")
    if (dir.includes("\\")) throw bad("has a backslash")
    if (/[*?[\]{}!]/.test(dir)) throw bad("is a glob")
    for (const segment of dir.split("/")) if (segment === "" || segment === "." || segment === "..") throw bad(segment === ".." ? "leaves the package" : "has an empty or `.` segment")
    return dir
}

/**
 * Validates a `sources` field (`package.json` `libstylist.sources` or a checker config package's) and
 * returns its directories normalized (trailing slashes dropped), in the order given: a non-empty array of
 * package-relative posix directories — no leading `/` or drive, no backslash, no empty, `.` or `..`
 * segment, no glob characters — none listed twice or inside another. Throws otherwise.
 */
export function normalizeSources(raw: unknown, where = "libstylist config"): string[] {
    const hint = `sources are package-relative posix directories (["src"], ["app/pages/settings"])`
    if (!Array.isArray(raw) || raw.length === 0) throw new Error(`${where}.sources must be a non-empty array of directories — ${hint}`)
    const out: string[] = []
    for (const value of raw) {
        if (typeof value !== "string") throw new Error(`${where}.sources: ${JSON.stringify(value)} is not a directory — ${hint}`)
        const dir = value.replace(/\/+$/, "")
        const bad = (why: string) => new Error(`${where}.sources: "${value}" ${why} — ${hint}`)
        if (!dir) throw bad("names no directory")
        if (dir.startsWith("/") || /^[A-Za-z]:/.test(dir)) throw bad("is absolute")
        if (dir.includes("\\")) throw bad("has a backslash")
        if (/[*?[\]{}!]/.test(dir)) throw bad("is a glob")
        for (const segment of dir.split("/")) if (segment === "" || segment === "." || segment === "..") throw bad(segment === ".." ? "leaves the package" : "has an empty or `.` segment")
        const other = out.find((o) => o === dir || dir.startsWith(`${o}/`) || o.startsWith(`${dir}/`))
        if (other !== undefined) throw bad(other === dir ? "is listed twice" : `nests with "${other}" (a file would be read twice)`)
        out.push(dir)
    }
    return out
}

/**
 * The source directories the `package.json` in `packageDir` declares (`libstylist.sources`, validated by
 * {@link normalizeSources}), or null when it declares none — no `package.json`, no `libstylist` field or
 * no `sources` in it. Throws on a malformed field.
 */
export function declaredSources(packageDir: string): string[] | null {
    const pkgPath = join(resolve(packageDir), "package.json")
    if (!existsSync(pkgPath)) return null
    const field = (JSON.parse(readFileSync(pkgPath, "utf8")) as { libstylist?: { sources?: unknown } }).libstylist
    return isObject(field) && field.sources !== undefined ? normalizeSources(field.sources, `${pkgPath} libstylist`) : null
}

/**
 * Normalizes a `namespaces` field (`package.json` or the checker config) against the package's base
 * config: every key is a directory ({@link normalizeNamespaceDir}), every value a namespace or
 * `{ namespace, segment?, word? }`, and every namespace names tags one way — two directories of one
 * namespace agree on its segment and word, and a directory can't rename the base namespace. Returns
 * the directories longest first (the order {@link namespaceDirOf} matches in). Throws on any problem.
 */
export function normalizeNamespaces(raw: unknown, base: PackageStylistConfig, where = "libstylist config"): DirectoryNamespace[] {
    if (raw === undefined) return []
    if (!isObject(raw)) throw new Error(`${where}.namespaces must be an object of package-relative directory → namespace`)
    const out: DirectoryNamespace[] = []
    const byNamespace = new Map<string, { config: PackageStylistConfig; source: string }>([[base.namespace, { config: base, source: `the base namespace "${base.namespace}"` }]])
    for (const [key, value] of Object.entries(raw)) {
        const dir = normalizeNamespaceDir(key, where)
        const at = `${where}.namespaces["${key}"]`
        if (out.some((d) => d.dir === dir)) throw new Error(`${at}: the directory "${dir}" is listed twice`)
        let entry: { namespace?: unknown; segment?: unknown; word?: unknown }
        if (typeof value === "string") entry = { namespace: value }
        else if (isObject(value)) {
            for (const k of Object.keys(value)) if (!["namespace", "segment", "word"].includes(k)) throw new Error(`${at}: unknown key "${k}" (allowed: namespace, segment, word)`)
            entry = value
        } else throw new Error(`${at} must be a namespace or { namespace, segment?, word? }`)
        for (const k of ["namespace", "segment", "word"] as const) if (entry[k] !== undefined && typeof entry[k] !== "string") throw new Error(`${at}.${k} must be a string`)
        const config = normalizePackageConfig(
            { prefix: base.prefix, hashLength: base.hashLength, namespace: entry.namespace as string | undefined, segment: entry.segment as string | undefined, word: entry.word as string | undefined },
            at,
        )
        const prev = byNamespace.get(config.namespace)
        if (prev && (prev.config.segment !== config.segment || prev.config.word !== config.word)) {
            throw new Error(
                `${at} names namespace "${config.namespace}" with segment "${config.segment}" and word "${config.word}", but ${prev.source} uses segment "${prev.config.segment}" and word "${prev.config.word}" — a namespace names tags one way`,
            )
        }
        byNamespace.set(config.namespace, prev ?? { config, source: `namespaces["${key}"]` })
        out.push({ dir, config })
    }
    return out.sort((a, b) => b.dir.length - a.dir.length || (a.dir < b.dir ? -1 : 1))
}

/**
 * The directory namespace a package-relative posix path falls in: the longest `namespaces` directory
 * containing it (`src/render/Row.tsx` is in `src/render`; `src/renderer/Row.tsx` is not), or null for
 * the base namespace. `namespaces` must be longest first, as {@link normalizeNamespaces} returns them.
 */
export function namespaceDirOf(namespaces: readonly DirectoryNamespace[], relPath: string): DirectoryNamespace | null {
    for (const ns of namespaces) if (relPath === ns.dir || relPath.startsWith(`${ns.dir}/`)) return ns
    return null
}

/** A package whose `package.json` declares a libstylist namespace. */
export interface LibstylistPackage {
    /** The directory holding the `package.json`. */
    dir: string
    /** The package's base config (its top-level `namespace`). */
    base: PackageStylistConfig
    /** Its directory namespaces, longest directory first. */
    namespaces: readonly DirectoryNamespace[]
}

/** The config one file resolves to (SPEC §8). */
export interface ResolvedPackageConfig {
    /** The package directory (holding the `package.json`). */
    dir: string
    /** The file's effective config: its directory namespace's, or the package's base config. */
    config: PackageStylistConfig
    /** The package's base config. */
    base: PackageStylistConfig
    /** The `namespaces` directory the file sits in (`src/render`), or null in the base namespace. */
    subdir: string | null
    /** Every directory namespace of the package, longest first. */
    namespaces: readonly DirectoryNamespace[]
}

const packageCache = new Map<string, LibstylistPackage | null>()

/**
 * Finds the nearest `package.json` above `file` that declares a `libstylist` field with a namespace,
 * and returns the package: its directory, base config and directory namespaces. `null` when the file
 * belongs to no configured package. Cached per directory — the package, never a file's namespace, so
 * sibling directories in different namespaces share the lookup.
 */
export function findLibstylistPackage(file: string): LibstylistPackage | null {
    let dir = dirname(resolve(file))
    const visited: string[] = []
    const settle = (hit: LibstylistPackage | null) => {
        for (const v of visited) packageCache.set(v, hit)
        return hit
    }
    for (;;) {
        if (packageCache.has(dir)) return settle(packageCache.get(dir) ?? null)
        visited.push(dir)
        const pkgPath = join(dir, "package.json")
        if (existsSync(pkgPath)) {
            const pkg = JSON.parse(readFileSync(pkgPath, "utf8"))
            const raw = pkg.libstylist as RawPackageStylistConfig | undefined
            if (raw && raw.namespace) {
                const base = normalizePackageConfig(raw, pkgPath)
                return settle({ dir, base, namespaces: normalizeNamespaces(raw.namespaces, base, pkgPath) })
            }
        }
        const parent = dirname(dir)
        if (parent === dir) return settle(null)
        dir = parent
    }
}

/** The effective config of `file` in `pkg`: the longest `namespaces` directory it sits in, else the base. */
export function packageConfigOf(pkg: LibstylistPackage, file: string): ResolvedPackageConfig {
    const rel = relative(pkg.dir, resolve(file)).split(sep).join("/")
    const hit = rel.startsWith("../") || rel === ".." ? null : namespaceDirOf(pkg.namespaces, rel)
    return { dir: pkg.dir, config: hit?.config ?? pkg.base, base: pkg.base, subdir: hit?.dir ?? null, namespaces: pkg.namespaces }
}

/**
 * The config a source file is compiled, linted and named with: the nearest configured package above
 * it, and within it the namespace of the longest `namespaces` directory the file sits in (else the
 * package's own). `null` when the file belongs to no configured package. Throws on a malformed config.
 */
export function resolvePackageConfig(file: string): ResolvedPackageConfig | null {
    const pkg = findLibstylistPackage(file)
    return pkg ? packageConfigOf(pkg, file) : null
}

const libstylistPackageCache = new Map<string, boolean>()

/** `@scope/name/sub` → `@scope/name`, `name/sub` → `name`. */
const packageNameOf = (specifier: string): string => specifier.split("/").slice(0, specifier.startsWith("@") ? 2 : 1).join("/")

/**
 * True when the package `fromFile` imports `specifier` from (resolved through the node_modules above it)
 * declares a libstylist `prefix` — a libstylist component library, whose components' cx() forwards only
 * the parts and markers they receive. Shared by ESLint (data-in-cx, cx-args) and the codemod.
 */
export function isLibstylistPackage(fromFile: string, specifier: string): boolean {
    const name = packageNameOf(specifier)
    const start = dirname(resolve(fromFile))
    const key = `${start}\0${name}`
    const hit = libstylistPackageCache.get(key)
    if (hit !== undefined) return hit
    let result = false
    for (let dir = start; ; ) {
        const pkg = join(dir, "node_modules", name, "package.json")
        if (existsSync(pkg)) {
            try {
                const field = (JSON.parse(readFileSync(pkg, "utf8")) as { libstylist?: { prefix?: unknown } }).libstylist
                result = !!field && typeof field.prefix === "string"
            } catch {
                result = false
            }
            break
        }
        const parent = dirname(dir)
        if (parent === dir) break
        dir = parent
    }
    libstylistPackageCache.set(key, result)
    return result
}

const declaresLibstylistCache = new Map<string, boolean>()

/**
 * True when the nearest `package.json` above `file` declares a libstylist `prefix` — `file` belongs to
 * a libstylist component library, such as a linked design-system dist (`…/components/dist/index.d.ts`)
 * or its copy in node_modules. The checker treats a component declared there as a libstylist delegate,
 * not a third-party one (its own checker enforces forwarding on it). Cached per directory.
 */
export function declaresLibstylist(file: string): boolean {
    let dir = dirname(resolve(file))
    const visited: string[] = []
    let result = false
    for (;;) {
        const hit = declaresLibstylistCache.get(dir)
        if (hit !== undefined) {
            result = hit
            break
        }
        visited.push(dir)
        const pkg = join(dir, "package.json")
        if (existsSync(pkg)) {
            try {
                const field = (JSON.parse(readFileSync(pkg, "utf8")) as { libstylist?: { prefix?: unknown } }).libstylist
                result = !!field && typeof field.prefix === "string"
            } catch {
                result = false
            }
            break
        }
        const parent = dirname(dir)
        if (parent === dir) break
        dir = parent
    }
    for (const v of visited) declaresLibstylistCache.set(v, result)
    return result
}

/**
 * Walks up from `from` to the monorepo root (the directory holding pnpm-workspace.yaml or .git). Outside
 * any checkout (a Docker build context, a fresh scaffold) it falls back to the nearest directory with a
 * package.json — the package root, so `data-file-source` stays `src/Counter.tsx:20`, never a bare file
 * name — and only then to `from` itself.
 */
export function findRepoRoot(from: string): string {
    let dir = resolve(from)
    let nearestPackage: string | null = null
    for (;;) {
        if (existsSync(join(dir, "pnpm-workspace.yaml")) || existsSync(join(dir, ".git"))) return dir
        if (nearestPackage === null && existsSync(join(dir, "package.json"))) nearestPackage = dir
        const parent = dirname(dir)
        if (parent === dir) return nearestPackage ?? resolve(from)
        dir = parent
    }
}

/** Clears cached package configs (tests, watch mode). */
export function clearConventionsCache(): void {
    packageCache.clear()
    libstylistPackageCache.clear()
    declaresLibstylistCache.clear()
}
