// Renders the per-package JSX type files: the hand-kept `types/stylist.d.ts` stub and the
// generated `types/stylist-tags.gen.d.ts`. Output is deterministic: sorted keys, LF line endings,
// and a trailing newline.
import { PREFIX_RE, TAG_RE } from "../conventions/index.js"
import { isIdentityName } from "../naming/index.js"

/** Module specifier of the hand-written JSX typings (`jsx/index.d.ts`). */
export const JSX_TYPES_MODULE = "@livesession/libstylist/jsx"

export interface RenderTypesOptions {
    /** Module the files import the JSX typings from. @default "@livesession/libstylist/jsx" */
    jsxModule?: string
    /** The package's source directories the tags come from (package-relative), named in the header. @default ["src"] */
    sources?: readonly string[]
}

export interface StubOptions extends RenderTypesOptions {
    /**
     * Also accept every `<prefix>-*` tag through the template-literal key of `StylistTagMap`
     * (TypeScript 5.x only). Off by default: the key enters `keyof JSX.IntrinsicElements`, and then
     * every JSX tag typed `React.ElementType` (`<As>`) fails with TS2604 on TS 4.9 and 5.x.
     * @default false
     */
    tagMap?: boolean
}

const assertPrefix = (prefix: string, where: string): void => {
    if (!PREFIX_RE.test(prefix)) throw new Error(`${where}: prefix "${prefix}" must match ${PREFIX_RE}`)
}

/**
 * Sorts, deduplicates and validates custom tag names. A name that isn't a valid custom-element
 * name (`elo-x`, lowercase, hyphenated) throws, and so does one outside `prefix` when it's given.
 */
export function normalizeTags(tags: Iterable<string>, where = "libstylist gen-types", prefix?: string): string[] {
    const out = new Set<string>()
    for (const tag of tags) {
        if (!TAG_RE.test(tag)) throw new Error(`${where}: "${tag}" is not a valid custom-element tag (${TAG_RE})`)
        if (prefix !== undefined && !isIdentityName(tag, prefix)) throw new Error(`${where}: "${tag}" is not a "${prefix}-*" tag`)
        out.add(tag)
    }
    return [...out].sort()
}

/**
 * The content of `types/stylist-tags.gen.d.ts`: one explicit `React.JSX.IntrinsicElements` key
 * per `<prefix>-*` custom tag, typed as `StylistHostProps`. These keys are how every JSX custom
 * tag type-checks, on TS 4.9 and 5.x, literal (`<elo-x>`) or held in a variable (`<Tag>`).
 */
export function renderTagTypes(prefix: string, tags: Iterable<string>, options: RenderTypesOptions = {}): string {
    assertPrefix(prefix, "renderTagTypes")
    const sorted = normalizeTags(tags, "renderTagTypes", prefix)
    const jsxModule = options.jsxModule ?? JSX_TYPES_MODULE
    const lines = [
        `// Generated by \`libstylist gen-types\` from the JSX under ${(options.sources ?? ["src"]).map((dir) => `${dir}/`).join(", ")}. Do not edit.`,
        "// `libstylist gen-types --check` fails when this file is stale.",
        "//",
        `// One explicit key per \`${prefix}-*\` custom tag this package renders. TypeScript checks JSX custom`,
        "// tags against explicit IntrinsicElements keys: TS 4.9 ignores template-literal keys for JSX tags,",
        `// no version applies them to a tag held in a variable (\`const Tag = "${prefix}-x"; <Tag />\`), and`,
        "// such a key would break every `React.ElementType` JSX tag (TS2604).",
    ]
    if (sorted.length === 0) {
        lines.push(`// No \`${prefix}-*\` custom tags found.`, "export {}")
        return lines.join("\n") + "\n"
    }
    lines.push(
        `import type { StylistHostProps } from ${JSON.stringify(jsxModule)}`,
        "",
        'declare module "react" {',
        "    namespace JSX {",
        "        interface IntrinsicElements {",
        ...sorted.map((tag) => `            ${JSON.stringify(tag)}: StylistHostProps`),
        "        }",
        "    }",
        "}",
    )
    return lines.join("\n") + "\n"
}

/**
 * The content of a package's hand-kept `types/stylist.d.ts`. It loads the JSX typings from
 * `@livesession/libstylist/jsx` (failing with TS2307 when the package is missing); the tags come
 * from the generated `stylist-tags.gen.d.ts` next to it. `tagMap: true` adds the TS 5.x-only
 * `StylistTagMap` key, at the cost described on {@link StubOptions.tagMap}.
 */
export function stylistTypesStub(prefix: string, options: StubOptions = {}): string {
    assertPrefix(prefix, "stylistTypesStub")
    const jsxModule = JSON.stringify(options.jsxModule ?? JSX_TYPES_MODULE)
    const lines = [
        `// libstylist JSX types for this package (prefix "${prefix}"). Created by \`libstylist gen-types\`.`,
        "// Kept by hand; include the types/ directory in the package tsconfig.",
        "//",
        "// Loads the libstylist JSX typings. The `" + prefix + "-*` tags are declared by the explicit keys that",
        "// `libstylist gen-types` writes next to this file, in stylist-tags.gen.d.ts.",
    ]
    if (!options.tagMap) {
        lines.push(`import type {} from ${jsxModule}`, "")
        return lines.join("\n")
    }
    lines.push(
        "//",
        `// The StylistTagMap key below also accepts undeclared \`${prefix}-*\` tags on TypeScript 5.x. It makes`,
        "// every JSX tag typed `React.ElementType` fail with TS2604, on every TypeScript version.",
        `import type { StylistTagMap } from ${jsxModule}`,
        "",
        'declare module "react" {',
        "    namespace JSX {",
        `        interface IntrinsicElements extends StylistTagMap<${JSON.stringify(prefix)}> {}`,
        "    }",
        "}",
        "",
    )
    return lines.join("\n")
}
