// `libstylist gen-types`: scanning JSX custom tags, rendering the generated tag file and the
// stub, and the --check / write flow. test/types-compile.test.ts compiles the output.
import assert from "node:assert/strict"
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, relative, resolve } from "node:path"
import { test } from "node:test"
import { fileURLToPath } from "node:url"

import { clearConventionsCache } from "../src/conventions/index.js"
import {
    STUB_TYPES_FILE,
    TAG_TYPES_FILE,
    checkTagTypes,
    collectJsxTags,
    genTagTypes,
    jsxTagNames,
    listSourceFiles,
    renderTagTypes,
    scanCustomTags,
    stylistTypesStub,
    writeTagTypes,
    writeTypesStub,
} from "../src/typesgen/index.js"
import { designSystemPath, skipWithoutDesignSystem } from "./design-system.js"

const here = dirname(fileURLToPath(import.meta.url))
const fixtureDir = join(here, "fixtures", "types")

const FIXTURE_TAGS = ["elo-alert", "elo-alert-badge", "elo-alert-spaced", "elo-alert-title", "elo-player-topbar", "elo-player-topbar-url"]

const withTemp = (fn: (dir: string) => void) => {
    const dir = mkdtempSync(join(tmpdir(), "libstylist-types-"))
    try {
        fn(dir)
    } finally {
        rmSync(dir, { recursive: true, force: true })
    }
}

test("collectJsxTags: opening and self-closing custom tags only", () => {
    const code = [
        "const a = <elo-alert data-x cx=\"root\"><elo-alert-title /></elo-alert>",
        "const b = <button elo-button elo-other=\"\" />", // markers are attributes
        "const c = <Modal.Header /> // <elo-in-a-comment>",
        "const d = <app-dock />", // another prefix
        "const e = \"<elo-in-a-string>\"",
        "const f = `<elo-in-a-template>`",
        "const g = <svg:rect />", // namespaced name
        "const h = <elo-Bad />", // not a valid identity tag
        "const i = <div title=\"<elo-in-an-attribute>\">{/* <elo-in-jsx-comment> */}</div>",
        "const j = <><elo-alert /></>",
    ].join("\n")
    assert.deepEqual(collectJsxTags(code, "x.tsx", "elo"), ["elo-alert", "elo-alert-title"])
    assert.deepEqual(collectJsxTags(code, "x.tsx", "app"), ["app-dock"])
    assert.deepEqual(jsxTagNames(code, "x.tsx"), ["elo-alert", "elo-alert-title", "app-dock", "elo-Bad", "elo-alert"])
})

test("collectJsxTags: whitespace and comments between < and the name, in a file with no literal <elo-", () => {
    // JSX allows both; TypeScript checks these tags like any other, so they need generated keys
    assert.deepEqual(collectJsxTags("const a = < elo-spaced />\n", "a.tsx", "elo"), ["elo-spaced"])
    assert.deepEqual(collectJsxTags("const b = <\n    elo-newline\n/>\n", "b.tsx", "elo"), ["elo-newline"])
    assert.deepEqual(collectJsxTags("const c = </* why */elo-commented></ elo-commented>\n", "c.tsx", "elo"), ["elo-commented"])
    // A prefix mention outside JSX is parsed and yields nothing
    assert.deepEqual(collectJsxTags('const d = "elo-alert"\n', "d.tsx", "elo"), [])
})

test("collectJsxTags: .ts files parse with generics and yield nothing; parse errors name the file", () => {
    assert.deepEqual(collectJsxTags("// <elo-x>\nexport const pick = <T,>(xs: Array<T>) => xs[0]\nconst y = <string>(\"<elo-y>\" as unknown)\n", "a.ts", "elo"), [])
    assert.deepEqual(collectJsxTags("export const x = 1", "a.tsx", "elo"), [], "no prefix text → not parsed at all")
    assert.throws(() => collectJsxTags("const x = <elo-a>", "broken.tsx", "elo"), /cannot parse broken\.tsx/)
})

test("listSourceFiles / scanCustomTags on the fixture package", () => {
    const files = listSourceFiles(join(fixtureDir, "src")).map((f) => relative(fixtureDir, f))
    assert.deepEqual(files, ["src/alert.tsx", "src/nested/player-top-bar.tsx", "src/notes.ts"])
    assert.deepEqual(scanCustomTags(fixtureDir, "elo"), FIXTURE_TAGS)
    assert.deepEqual(scanCustomTags(join(fixtureDir, "missing"), "elo"), [])
})

test("genTagTypes: header, sorted explicit React.JSX keys, extra tags merged", () => {
    const out = genTagTypes({ packageDir: fixtureDir, prefix: "elo", tags: ["elo-zeta", "elo-alert", "elo-beta"] })
    assert.ok(out.startsWith("// Generated by `libstylist gen-types` from the JSX under src/. Do not edit.\n"))
    assert.ok(out.includes('import type { StylistHostProps } from "@livesession/libstylist/jsx"\n'))
    assert.ok(out.includes('declare module "react" {\n    namespace JSX {\n        interface IntrinsicElements {\n'))
    assert.ok(!out.includes("declare global"), "@types/react 19 has no global JSX namespace; only React.JSX is used")
    const keys = [...out.matchAll(/^ {12}"([^"]+)": StylistHostProps$/gm)].map((m) => m[1])
    assert.deepEqual(keys, [...FIXTURE_TAGS, "elo-beta", "elo-zeta"].sort())
    assert.ok(out.endsWith("}\n") && !out.includes("\r"))
    assert.equal(genTagTypes({ packageDir: fixtureDir, prefix: "elo" }), genTagTypes({ packageDir: fixtureDir, prefix: "elo" }), "deterministic")
})

test("genTagTypes: validation, empty output, custom jsx module", () => {
    assert.throws(() => genTagTypes({ packageDir: fixtureDir, prefix: "elo", tags: ["Elo-Bad"] }), /not a valid custom-element tag/)
    assert.throws(() => genTagTypes({ packageDir: fixtureDir, prefix: "elo", tags: ["nohyphen"] }), /not a valid custom-element tag/)
    assert.throws(() => genTagTypes({ packageDir: fixtureDir, prefix: "El" }), /must match/)
    // Extra tags must belong to the prefix, like the scanned ones
    assert.throws(() => genTagTypes({ packageDir: fixtureDir, prefix: "elo", tags: ["app-shell"] }), /"app-shell" is not a "elo-\*" tag/)
    assert.throws(() => renderTagTypes("elo", ["eloalert-x"]), /is not a "elo-\*" tag/)
    const empty = renderTagTypes("app", [])
    assert.ok(empty.includes("// No `app-*` custom tags found.\nexport {}\n"))
    assert.ok(!empty.includes("import"))
    assert.ok(renderTagTypes("elo", ["elo-x"], { jsxModule: "../jsx" }).includes('from "../jsx"'))
})

test("genTagTypes: prefix defaults to the package.json libstylist config", () => {
    withTemp((dir) => {
        writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "fixture", libstylist: { prefix: "app", namespace: "core" } }))
        cpSync(join(fixtureDir, "src"), join(dir, "src"), { recursive: true })
        writeFileSync(join(dir, "src", "shell.tsx"), "export const S = () => <app-shell data-x=\"1\" />\n")
        clearConventionsCache()
        const out = genTagTypes({ packageDir: dir })
        assert.deepEqual([...out.matchAll(/"([a-z0-9-]+)": StylistHostProps/g)].map((m) => m[1]), ["app-shell"])
        assert.ok(stylistTypesStub("app", { tagMap: true }).includes('StylistTagMap<"app">'))
    })
    withTemp((dir) => {
        clearConventionsCache()
        assert.throws(() => genTagTypes({ packageDir: join(dir, "nowhere") }), /no prefix given/)
    })
})

test("checked-in fixture files are current (what `gen-types --check` runs in CI)", () => {
    const check = checkTagTypes({ packageDir: fixtureDir, prefix: "elo" })
    assert.equal(check.file, resolve(fixtureDir, TAG_TYPES_FILE))
    assert.ok(check.ok, `stale ${TAG_TYPES_FILE}; regenerate it with genTagTypes`)
    assert.equal(readFileSync(join(fixtureDir, STUB_TYPES_FILE), "utf8"), stylistTypesStub("elo"))
})

test("checkTagTypes / writeTagTypes: missing, stale, CRLF and idempotent writes", () => {
    withTemp((dir) => {
        cpSync(join(fixtureDir, "src"), join(dir, "src"), { recursive: true })
        const opts = { packageDir: dir, prefix: "elo" }

        const missing = checkTagTypes(opts)
        assert.equal(missing.ok, false)
        assert.equal(missing.actual, null)

        assert.deepEqual(writeTagTypes(opts), { file: resolve(dir, TAG_TYPES_FILE), changed: true })
        assert.deepEqual(writeTagTypes(opts), { file: resolve(dir, TAG_TYPES_FILE), changed: false })
        assert.equal(checkTagTypes(opts).ok, true)

        writeFileSync(resolve(dir, TAG_TYPES_FILE), checkTagTypes(opts).expected.replace(/\n/g, "\r\n"))
        assert.equal(checkTagTypes(opts).ok, true, "CRLF checkouts are not stale")

        writeFileSync(join(dir, "src", "added.tsx"), "export const A = () => <elo-added />\n")
        const stale = checkTagTypes(opts)
        assert.equal(stale.ok, false)
        assert.ok(stale.expected.includes('"elo-added": StylistHostProps'))
        assert.ok(stale.actual !== null && !stale.actual.includes("elo-added"))

        const custom = join(dir, "out", "tags.d.ts")
        assert.equal(writeTagTypes({ ...opts, file: custom }).changed, true)
        assert.ok(existsSync(custom))
    })
})

test("stylistTypesStub / writeTypesStub: loads the typings only, tag map opt-in, created once, never overwritten by default", () => {
    const stub = stylistTypesStub("elo")
    // A type-only import: it fails loudly (TS2307) when libstylist is missing, unlike `export type {} from`
    assert.ok(stub.endsWith('import type {} from "@livesession/libstylist/jsx"\n'))
    assert.ok(!stub.includes("StylistTagMap") && !stub.includes("declare module"), "the template-literal key breaks React.ElementType tags")
    assert.ok(stylistTypesStub("elo", { jsxModule: "../jsx" }).includes('import type {} from "../jsx"\n'))

    const tagMap = stylistTypesStub("elo", { tagMap: true })
    assert.ok(tagMap.includes('import type { StylistTagMap } from "@livesession/libstylist/jsx"\n'))
    assert.ok(tagMap.includes('        interface IntrinsicElements extends StylistTagMap<"elo"> {}\n'))
    assert.ok(tagMap.includes("TS2604"), "the opt-in states its cost")
    assert.ok(tagMap.endsWith("}\n") && !tagMap.includes("\r"))
    assert.throws(() => stylistTypesStub("1x"), /must match/)
    withTemp((dir) => {
        const file = resolve(dir, STUB_TYPES_FILE)
        assert.deepEqual(writeTypesStub({ packageDir: dir, prefix: "elo" }), { file, written: true })
        writeFileSync(file, "// edited by hand\n")
        assert.deepEqual(writeTypesStub({ packageDir: dir, prefix: "elo" }), { file, written: false })
        assert.equal(readFileSync(file, "utf8"), "// edited by hand\n")
        assert.equal(writeTypesStub({ packageDir: dir, prefix: "elo", force: true }).written, true)
        assert.equal(readFileSync(file, "utf8"), stub)
        assert.equal(writeTypesStub({ packageDir: dir, prefix: "elo", force: true, tagMap: true }).written, true)
        assert.equal(readFileSync(file, "utf8"), tagMap)
    })
})

// The design system's real sources: the checkout LIBSTYLIST_DESIGN_SYSTEM names (./design-system.ts); skipped without it.
test("smoke: every real DS package source parses; tags found are prefixed and generation succeeds", { skip: skipWithoutDesignSystem }, () => {
    const packages = ["components", "app-ui", "player", "gram", "infinity", "ai"].map((p) => designSystemPath("packages", p))
    let parsed = 0
    for (const packageDir of packages) {
        if (!existsSync(join(packageDir, "src"))) continue
        for (const file of listSourceFiles(join(packageDir, "src"))) {
            for (const name of jsxTagNames(readFileSync(file, "utf8"), file)) assert.match(name, /-/, file)
            parsed++
        }
        const out = genTagTypes({ packageDir })
        for (const m of out.matchAll(/"([^"]+)": StylistHostProps/g)) assert.match(m[1], /^elo-/)
    }
    assert.ok(parsed > 100, `parsed only ${parsed} DS source files`)
})
