// generated by libstylist (`libstylist build`) — do not edit; `libstylist build --check` fails on drift
import "./member-row.css"
import "./render-team.css"
import "./settings-page.css"

/** member-row.css */
export const memberRow = {
    name: "_cxclass_crm-95gosh",
    root: "_cxclass_crm-lpycl7",
    $tags: {
        MemberRow: "crm-settings-memberrow",
    },
} as const

/** render-team.css */
export const renderTeam = {
    list: "_cxclass_crm-01cdtl",
    root: "_cxclass_crm-o2ijo3",
    $tags: {
        RenderTeam: "crm-settings-renderteam",
    },
} as const

/** settings-page.css */
export const settingsPage = {
    root: "_cxclass_crm-0hc2dr",
    title: "_cxclass_crm-0fg2kk",
    $tags: {
        SettingsPage: "crm-settings-page",
    },
} as const
