// Generated by `libstylist gen-types` from the JSX under src/. Do not edit.
// `libstylist gen-types --check` fails when this file is stale.
//
// One explicit key per `elo-*` custom tag this package renders. TypeScript checks JSX custom
// tags against explicit IntrinsicElements keys: TS 4.9 ignores template-literal keys for JSX tags,
// no version applies them to a tag held in a variable (`const Tag = "elo-x"; <Tag />`), and
// such a key would break every `React.ElementType` JSX tag (TS2604).
import type { StylistHostProps } from "@livesession/libstylist/jsx"

declare module "react" {
    namespace JSX {
        interface IntrinsicElements {
            "elo-alert": StylistHostProps
            "elo-alert-badge": StylistHostProps
            "elo-alert-spaced": StylistHostProps
            "elo-alert-title": StylistHostProps
            "elo-player-topbar": StylistHostProps
            "elo-player-topbar-url": StylistHostProps
        }
    }
}
