// `@livesession/libstylist/postcss`: the stylesheet side of libstylist (SPEC §4).
export { PLUGIN_NAME, stylist, type StylistNaming, type StylistOptions, type StylistRoot, type StylistSink } from "./plugin.js"
export {
    collectSheet,
    scopeFromFile,
    type SheetComponentRef,
    type SheetCxRef,
    type SheetInfo,
    type SheetIssue,
    type SheetIssueKind,
    type SheetMeta,
    type SheetRoot,
} from "./collect.js"
export {
    DIRECTIVE_NAME,
    DirectiveError,
    OVERRIDE_GRAMMAR,
    RESET_GRAMMAR,
    parseDirective,
    readDirectives,
    readOverrideDirectives,
    type OverrideDirective,
    type OverrideDirectiveIssue,
    type OverrideDirectives,
    type OverrideTargetRef,
    type ResetDirective,
    type RootDirective,
    type SheetDirectives,
    type StylistDirective,
} from "./directives.js"
export {
    OVERRIDE_PLUGIN_NAME,
    collectOverrideSheet,
    identitySelector,
    overrideKeyframesName,
    overridePartList,
    overrideSheetId,
    stylistOverride,
    unknownPartMessage,
    withinSelector,
    wrapInLayer,
    type OverrideClassUse,
    type OverrideSheetInfo,
    type OverrideSheetMeta,
    type StylistOverrideOptions,
    type StylistOverrideSink,
} from "./override.js"
export {
    LAYOUT_CONTAINER_PROPS,
    LAYOUT_ITEM_MARGINS,
    LAYOUT_ITEM_MINIMA,
    LAYOUT_ITEM_PROPS,
    LAYOUT_ITEM_SIZES,
    RESET_PLUGIN_NAME,
    acknowledgedDeclarations,
    acknowledges,
    attributeMatcher,
    classifySubject,
    formatResetReport,
    formatResetReports,
    identityMatcher,
    layoutKinds,
    longhandsOf,
    ofSelectors,
    resetComment,
    resetCss,
    resetGuard,
    resetReports,
    resetStylesheet,
    selectorConditions,
    stylistReset,
    subjectCompound,
    touchedTargets,
    type AcknowledgedDeclaration,
    type DroppedDeclaration,
    type DroppedRule,
    type ForeignRule,
    type GuardedSelector,
    type LayoutKind,
    type ResetCssOptions,
    type ResetCssResult,
    type ResetLayoutNote,
    type ResetOutcome,
    type ResetReport,
    type ResetReportLine,
    type ResetReportsOptions,
    type ResetStylesheet,
    type ResetTarget,
    type StylistResetOptions,
    type SubjectClass,
    type SubjectMatch,
    type SubjectMatcher,
} from "./reset.js"
export {
    importantConflicts,
    importantDeclarations,
    overlappingProperties,
    type ImportantConflict,
    type ImportantDeclaration,
} from "./important.js"
export { displayDefaultDeclarations, displayDefaultRule } from "./display.js"
export { compareSpecificity, formatSpecificity, specificity, specificityList, type Specificity } from "./specificity.js"
export {
    findClassSelectors,
    isClassAttribute,
    preludeSelectors,
    replacePreludeSelectors,
    type ClassSelectorHit,
    type PreludeSelector,
} from "./selectors.js"
export { isKeyframesAtRule, keyframesName, renameAnimationValue } from "./keyframes.js"
export {
    SelectorRefError,
    parseComponentRef,
    parseCxRef,
    replaceRefs,
    scanRefs,
    type ComponentRef,
    type CxRef,
    type SelectorRef,
    type SelectorRefKind,
} from "./refs.js"

export { stylist as default } from "./plugin.js"
