// `@livesession/libstylist/workspace`: tooling for a workspace of app packages that keep their sheets
// next to their sources (docs/CONFIG.md, "A workspace of app packages") — the packages of the config
// discovered from the workspace (`workspacePackages`, `partMapsFor`), the css groups of a package and
// the namespace of each of its sheets, and the build: the registry, each package's generated part-map
// module, the lock, and one sheet compiled into its cascade layer (`libstylist build`, and
// `stylistWorkspace()` from `@livesession/libstylist/vite` at import time) — plus the app's override
// sheets of a design system (`css.overrides`, SPEC §9): resolved, compiled into the overrides layer,
// their resets reported, their generated module.
export { listSheets, packageGroups, packageSheetGroups, sheetGroupName, sheetNaming, type GroupedPackage, type PackageSheetGroup } from "./groups.js"
export {
    DEFAULT_ENTRIES,
    DEFAULT_SHEETS,
    expandDirectoryGlob,
    partMapsFor,
    readPnpmWorkspaceGlobs,
    workspacePackages,
    type DiscoveredPackage,
    type PartMapsPackage,
    type WorkspacePackagesOptions,
} from "./packages.js"
export {
    DEFAULT_LOCK_FILE,
    DEFAULT_REGISTRY_FILE,
    DESIGN_SYSTEM_LAYERS,
    PART_MAP_HEADER,
    PART_MAP_MODULE,
    WorkspaceError,
    buildWorkspace,
    changedScopes,
    compileSheet,
    dependentSheets,
    loadWorkspace,
    planWorkspaceOutputs,
    renderPartMapModule,
    resolveLayers,
    runWorkspaceBuild,
    workspaceOf,
    workspaceOverrideSheet,
    workspaceSheetOwner,
    workspaceSourcePattern,
    writeWorkspaceOutputs,
    type BuildWorkspaceOptions,
    type CompiledSheet,
    type LoadWorkspaceOptions,
    type PlanOutputsOptions,
    type RunWorkspaceBuildOptions,
    type Workspace,
    type WorkspaceBuild,
    type WorkspaceBuildProblem,
    type WorkspaceBuildReport,
    type WorkspaceLayers,
    type WorkspaceOutput,
    type WorkspaceOverridesConfig,
    type WorkspacePackage,
    type WorkspaceSheet,
} from "./build.js"
export { BUILD_USAGE, runBuildCli, type BuildCliOptions } from "./cli.js"
export {
    DEFAULT_DESIGN_SYSTEM_REGISTRY,
    DEFAULT_OVERRIDES_LAYER,
    OVERRIDES_MODULE,
    bundleLayerProblem,
    collectOverrides,
    compileOverride,
    compileOverrideSheet,
    declaredLayerOrder,
    designSystemImportants,
    designSystemOf,
    designSystemStylesheets,
    findInstalledPackage,
    importantWarnings,
    isOverrideSheet,
    loadDesignSystems,
    overridePackageResolver,
    overrideReports,
    overridesLayerProblem,
    renderOverridesModule,
    resetKey,
    resetsOf,
    unbundledResets,
    type CollectOverridesOptions,
    type CompileOverrideOptions,
    type CompiledOverride,
    type CompiledOverrideSheet,
    type DeclaredLayer,
    type DesignSystem,
    type InstalledPackage,
    type OverrideReports,
    type WorkspaceOverrideSheet,
    type WorkspaceOverrides,
} from "./overrides.js"
